config/routes.rb
Rails.application.routes.draw do
  

  resources :products do
    resources :comments

  end

  devise_for :users

  resources :users

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  root 'static_pages#landing_page'

resources :orders, only: [:index, :show, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
  has_many :comments

def average_rating
	comments.average(:rating).to_f
end

validates :name, presence: true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  respond_to :json, :html
  before_action :set_product, only: [:show, :edit, :update, :destroy]
 
  # GET /products
  # GET /products.json
  def index
    search_term = params[:q]
    if Rails.env.development? && search_term.present?
      @products = Product.where("name LIKE ?", "%#{search_term}%")
    else
      @products = Product.all  
    end

    respond_with @products
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], per_page: 5)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
  end

app/helpers/products_helper.rb
module ProductsHelper
	def cache_key_for_products
		count          = Product.count
		max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
		"products/all-#{count}-#{max_updated_at}"
	end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
   <% @comments.each do |comment| %>
    <div class="row">
      <hr>
      <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
      	<% if signed_in? && current_user.admin? %>
        	<%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe,  product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
       </p>
      <div class="rated" data-score="<%= comment.rating %>"></div>
      <p><%= comment.body %></p>
    </div>
  <% end %>
  <%= will_paginate @comments %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container input-form">
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "name of bike", style: "resize:none" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control", style: "resize:none" %>
  </div>
  <div class="form-group">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, class: "form-control", style: "resize:none" %>
  </div>
  <div class="form-group">
    <%= f.label :color %><br>
    <%= f.text_field :color, class: "form-control", style: "resize:none" %>
  </div>
    <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control", style: "resize:none" %>
  </div>
  <div class="actions">
      <%= f.submit class: "btn btn-success" %>
    </div>
  </div>
</div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
 <div class="comments-form">
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <div class="form-group">
    	<%= f.label :body, "Comments" %><br>
    	<%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="rating"></div><br>
    <p><%= f.submit "Submit", class: "btn btn-primary" %>
    </p>
  </div>
 <% end %>
<% end %>

app/views/products/_product.html.erb
<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12" id="productimg">
	<%= image_tag(product.image_url, :class => "img-responsive") %>
</div>
<% cache product do %>
<div class="col-lg-16 col-md-6 col-sm-12 col-xs-12 productinfo">
	<p>Name: <%= product.name %></p>
	<p>Description: <%= product.description %></p>
	<p>Color: <%= product.color %></p>
	<p>Price: <%= product.price %></p></br>
	<% logger.debug "Product: #{product.name}"%>
</div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>String</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Color</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% cache(cache_key_for_products) do %>  
    <%= render @products %>
  <% end %>
  </tbody>
</table>
</div>
<br>

<button type="button" class="btn btn-primary"><%= link_to 'New Product', new_product_path %></button>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<div class="col-xs-12 col-md-6">

<% cache @product do %>

<div class="thumbnail">
  <%= image_tag(@product.image_url, class: "img-zoom", :data_zoom_image => @product.image_url) %>
</div>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>


<p>
  <strong>Color:</strong>
  <%= @product.color %>
</p>

<p>
  <strong>Price:</strong><span class="glyphicon glyphicon-euro"></span>
  <%= @product.price %>
</p>

<p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div>
</p>

<% end %>

<p>
<%= form_tag "/payments/create" do %>
  <% render partial: "shared/stripe_checkout_button" %>
<% end %>
</p>

</div>
</div>
</div>

<%= render 'new_comment' %>
<%= render 'comments' %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>