config/routes.rb
Rails.application.routes.draw do
  

  resources :products do
    resources :comments

  end

  devise_for :users

  resources :users

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  root 'static_pages#landing_page'

resources :orders, only: [:index, :show, :create, :destroy]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nameofapp</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand"<li><%= link_to "Bike Berlin", root_path %></li>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About",   static_pages_about_path  %><span class="sr-only">(current)</span></li>
        <li><%= link_to "Contact", static_pages_contact_path %></li>
      </ul>

      <ul class="nav pull-right">
        <li>
          <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          <% else %>
            <%= link_to('Login', new_user_session_path) %>
          <% end %>
        </li>
      </ul>

      <button type="button" class="btn btn-default navbar-btn">
        <%= form_tag("/products", method: "get") do %>
          <%= label_tag(:q, "Search for:") %>
          <%= text_field_tag(:q) %>
          <%= submit_tag("Search") %>
        <% end %>
    </button>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<h1>Welcome to Bike Berlin</h1>
<h2>Your source for used bikes in Berlin</h2>

<% if notice %>
  <p class="alert alert-warning" role="alert"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-info" role="alert"><%= alert %></p>
<% end %>
<%= yield %>

<footer class="site-footer">
&copy;  Kate Perris 2015
</footer>
</body>
</html>